### PR TITLE
fix(plugins/base): indepth mode

### PR DESCRIPTION
**Pull request by renbaoshuo**

### CODE REVIEW

**Comment by lowlighter** [comment]
Hi 👋 !

Thanks a lot for your pull request and this issue report 🙂 

I think the issue may be more from the "action inputs -> web inputs" converter, somewhere along this code part:
https://github.com/lowlighter/metrics/blob/2bbe50e9ae1785230f7603d7645e8e9a5fdd89c2/source/app/action/index.mjs#L359-L368

The `base` object should have the `indepth` properties assigned so it's passed down to the rendering engine below. Currently it's probably not properly extracted, but something along should fix it:

```js
const {base: parts, repositories: _repositories, indepth:_base_indepth, ...base} = metadata.plugins.base.inputs.action({core, preset}) 
//...
base.indepth = _base_indepth
```
___

`base.indepth` is the correct input name to use on web servers so changing the inputs definition would break it, plus since officially this setting was relased under the name `base_indepth`, users shouldn't have to patch it in their workflow, else it'd be considered as a breaking change

**Comment by renbaoshuo** [comment]
It doesn't work...

@lowlighter Could you help me on this? thanks.

**Comment by lowlighter** [comment]
Ok so it's a bit tricky because the `base` a plugin is a "legacy plugin" so it has some quirks.
It's not too far from what you've done though. 

Assigning `base.indepth` is actually useless because the parser expect `base["base.indepth"]` instead, but the inputs printer trim the plugin name so it needs to be just `indepth` for it.
```diff
     //Base content
     info.break()
-    const {base: parts, repositories: _repositories, ...base} = metadata.plugins.base.inputs.action({core, preset})
+    const {base: parts, repositories: _repositories, indepth: _base_indepth, ...base} = metadata.plugins.base.inputs.action({core, preset})
     conf.settings.repositories = _repositories
-    info.group({metadata, name: "base", inputs: {repositories: conf.settings.repositories, ...base}})
+    info.group({metadata, name: "base", inputs: {repositories: conf.settings.repositories, ...base, indepth: _base_indepth}})
     info("Base sections", parts)
     base.base = false
     for (const part of conf.settings.plugins.base.parts)
       base[`base.${part}`] = parts.includes(part)
+    base["base.indepth"] = _base_indepth
     Object.assign(q, base)
```

With the above, both the inputs display and the actual parameter get caught by the engine:
image

**Review by lowlighter — APPROVED** [review]

**Comment by lowlighter** [comment]
Thanks !

**Pull request merged**
