### PR TITLE
Add licenses plugin

### PR DESCRIPTION
**Pull request by lowlighter**
Add a new `📜 licenses` plugin, targetted for repositories' metrics to inform about licenses compliancy, permissions, limitations and conditions based on current license and licenses from used dependencies.

- Base metrics will display a few stats (nb of dependencies, known licenses and unknown licenses)
- `plugin_licenses_ratio` lets you display total ratio of each used licenses
- `plugin_licenses_legal` lets you display which permissions, limitations and conditions are implied by current license and licenses from used dependencies (inherited limitations and conditions will be indicated with a different icon while conflicting permissions will be removed)

It use [github/licensed](https://github.com/github/licensed) to detect licenses.

### Examples output:

Permissions, limitations and conditions:

Ratio:

Both can be of course combined in a single SVG output.

Disclaimer: This is not legal advice. Use at your own risk

### CODE REVIEW

**Comment by Milo123459** [comment]
I'm confused, this is just going to tell you the license you use the most?

**Comment by lowlighter** [comment]
What you mention is already available in user's metrics 🙂

This one is targetted exclusively for repositories metrics to display licenses compliancy, permissions, limitations and conditions (a bit like what is currently displayed by GitHub when going on a [LICENSE](https://github.com/lowlighter/metrics/blob/master/LICENSE) page, but metrics will also try to analyze dependencies licenses).

It's still not finished yet as I'm waiting for [github/licensed v2.14.4 release](https://github.com/github/licensed/pull/335), but it'll probably end up looking like this :


As you can see, there's legal rights from "base" license but also "inherited limitations" in this case, which would preventing patenting the code as a whole (i.e. including dependencies) since it is explicitely forbidden.

But it's just for informative purposes though, it cannot be used as legal advice 🙂

**Comment by Milo123459** [comment]
That PR is merged

**Comment by lowlighter** [comment]
@jonabc
Thought you might be interested seeing end result 🙂 :


There is still room for improvements, but I'll probably check again in the future. 
Seems that GitHub is missing some "common" licenses in their [GraphQL API](https://github.com/lowlighter/metrics/blob/master/source/plugins/licenses/queries/licenses.graphql) though (like ISC license for example)

Thanks again for your work!

**Comment by jonabc** [comment]
very cool, thanks for the ping!

**Pull request merged**
