### PR TITLE
normalize dates like the music played_at plugin

### PR DESCRIPTION
**Pull request by Milo123459**
Normalize's dates like the played_at plugin for the twitter plugin.
Preview:
image

Hope you enjoy :D

### CODE REVIEW

**Comment by Milo123459** [comment]
^ I also configured eslint because it wasn't doing anything.

**Comment by lowlighter** [comment]
Thanks for contributing!

Can you just keep only commit `74a6565` and remove the two last ones?
I'll merge it after

Thanks 🙂

**Comment by Milo123459** [comment]
@lowlighter I can't seem to revert the commits, is it possible for you to do so?

**Comment by lowlighter** [comment]
I don't have write access to forks, but you can easily do it through git command line 🙂 : 
```shell
git checkout twitter-dates
git reset HEAD~2 # Set head two commits before
git show # Check that you're on commit 74a6565 
git push --force
```

**Comment by Milo123459** [comment]
Did it work?

**Comment by Milo123459** [comment]
There we go, fixed!

**Review by lowlighter — APPROVED** [review]

**Pull request merged**
