### PR TITLE
Load all language colours

### LINKED ISSUE #339: Indepth language analysis doesn't load all language colors
Moving from #338
> Also what happened to Ruby's colour?
Screenshot_20210528-174447
&mdash;https://github.com/lowlighter/metrics/issues/338#issuecomment-850151030 by me

> When using indepth feature, colors aren't fetched from GitHub (I didn't check whether it's possible to get them through api).
If the color for the languages wasn't loaded beforehand through the GraphQL API (i.e. like the non-indepth behaviour), it defaults to the gray color.
&mdash;https://github.com/lowlighter/metrics/issues/338#issuecomment-850357833 by @lowlighter

### PR DESCRIPTION
**Pull request by Nixinova**
- Resolve #339 

Using the latest version of Nixinova/Linguist allows colors to be grabbed straight from it instead of the GH query.

### CODE REVIEW

**Comment by Nixinova** [comment]
Hm, my test may not be enough as everything in recent is also in most-used. Also unsure of the Vercel failure.

**Comment by Nixinova** [comment]
Yeah, currently misses Ruby, but does load Dockerfile.

image

**Comment by Nixinova** [comment]
Not sure why C isn't getting any colour...

image

**Comment by Nixinova** [comment]
Closing until I can figure out whats wrong without spamming Vercelbot

**Comment by Nixinova** [comment]
Got it working :tada:

image

**Review by lowlighter — APPROVED** [review]

**Comment by lowlighter** [comment]
Thanks a lot for your awesome contributions to the language plugin!

**Pull request merged**
