### PR TITLE
stargazers dates for months are now full

### PR DESCRIPTION
**Pull request by Milo123459**
img

Dates are now full!

### CODE REVIEW

**Comment by lowlighter** [comment]
Nice, though it requires a bit more css tweaks 🙂 

As you can see it offsets nearby segments (there is actually the same issue when you have thousands of stargazers) so when you'll reach December/November and other months with long names, everything will be out of place 😅

**Comment by Milo123459** [comment]
> Nice, though it requires a bit more css tweaks 🙂
> 
> As you can see it offsets nearby segments (there is actually the same issue when you have thousands of stargazers) so when you'll reach December/November and other months with long names, everything will be out of place 😅

Fun bug. I'll get to work!

**Comment by Milo123459** [comment]
Having no luck playing around with CSS, you got any ideas?

**Comment by lowlighter** [comment]
Not really.

I know that using mixing `position: absolute`, `overflow: hidden` and `position: relative` do the trick, but the later is broken on safari (at least ios) in svg contexts, so that's a no go. (a few properties dont' work properly on safari and it's pretty annoying).

Another problem is also that when next month will pop on the right, you'll have to do magic too, else it'll be outside the chart/image.

That's actually why it was truncated them in the first place, it was the easiest solution 🙂

**Comment by Milo123459** [comment]
Ah.

**Pull request closed without merging**
