### PR TITLE
update activity

### PR DESCRIPTION
**Pull request by Milo123459**
- main refactor
- the refactor is done maybe
- it wasnt

I haven't previewed this because I litreally can't, so, if possible send me screenshots of what it looks like.

Main features:
- Bold
- HREFs
- Looks cooler

### CODE REVIEW

**Comment by Milo123459** [comment]
^^ let me know if you have any feedback btw, I'm going out with some friends and I'll respond when I'm back, please be as detailed as possible!

**Comment by Milo123459** [comment]
It broke, I'll fix it when I get home, still appreciate feedback tho!

**Comment by lowlighter** [comment]
If possible, try to succeed setup your web instance (#106) so you can preview changes and also share them directly in PR, unfortunately I cannot afford to checkout on every branch and test manually, it would very time consuming 😅

From the diff I can't really see what changed, though I see you added hrefs links.
Unfortunately, these don't work on GitHub because metrics are actually displayed as an image (if you click on it, you'll be either redirected to source or a link wrapping your image) and AFAIK there's no way to bypass this GitHub restriction (I already attempted in the past but gave up) 😕 

Unless for new features additions I'd like to avoid changing too much visual style of main repo templates to keep consistency (actually, style hasn't changed since v1) and redesign is always a difficult task, as it's hard to satisfy everyone. I assume that users who sticked to main repo templates are more or less okay with its design, else I assume they'd probably forked it to customize it themselves.

Like #66, If you'd like to change how classic template is displayed, I'd suggest looking at [community templates](https://github.com/lowlighter/metrics/tree/master/source/templates/community). Basically you can just edit existing or create new template on a fork, and everyone will be able to use it through `setup_community_templates` option, without needing to merge it in main repo 🙂 

Hope that make sense 👍

**Comment by Milo123459** [comment]
Oh. What a shame you can't do that :(

**Comment by lowlighter** [comment]
Yeah 😕

I may have a long-term solution to implement this feature, but haven't digged to much into it for now. But hopefully one day it'll be possible 🙂

**Comment by Milo123459** [comment]
I submitted some feedback to github, I'll reopen this or when it's out 🗡️

**Pull request closed without merging**
